server:
  port: 8070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka 
      
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: bijoux-service-route
          uri: lb://BIJOUX
          predicates:
            - Path=/bijoux/**
        - id: user-service-route
          uri: lb://USERS-MICROSERVICE
          predicates:
            - Path=/users/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials